sudo: required
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  # see https://github.com/travis-ci/travis-ci/issues/10275
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install gcc || brew link --overwrite gcc; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install make; fi

script:
  - cmake --version
  - cmake -H. -Bbuild
  - cmake --build build --target all
  - cmake --build build --target test
