# ref: https://github.com/docker-library/official-images
name: arm64 Docker CMake

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      matrix:
        distro: [
          almalinux,
          alpine,
          debian,
          #fedora, # timeout
          #opensuse, # timeout
          rockylinux,
          ubuntu
        ]
      fail-fast: false
    name: arm64•${{matrix.distro}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Check docker
        run: |
          docker info
          docker buildx ls
      - name: Build env image
        run: make --directory=ci arm64_${{matrix.distro}}_env
      - name: Build devel project
        run: make --directory=ci arm64_${{matrix.distro}}_devel
      - name: Build project
        run: make --directory=ci arm64_${{matrix.distro}}_build
      - name: Test project
        run: make --directory=ci arm64_${{matrix.distro}}_test

      - name: Build install env image
        run: make --directory=ci arm64_${{matrix.distro}}_install_env
      - name: Build install devel project
        run: make --directory=ci arm64_${{matrix.distro}}_install_devel
      - name: Build install project
        run: make --directory=ci arm64_${{matrix.distro}}_install_build
      - name: Test install project
        run: make --directory=ci arm64_${{matrix.distro}}_install_test

  arm64_docker_cmake:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
